[rospy.client][INFO] 2017-10-13 16:36:14,484: init_node, name[/distance_collector], pid[31061]
[xmlrpc][INFO] 2017-10-13 16:36:14,485: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-10-13 16:36:14,487: ROS Slave URI: [http://wks-51-57:36088/]
[xmlrpc][INFO] 2017-10-13 16:36:14,487: Started XML-RPC server [http://wks-51-57:36088/]
[rospy.impl.masterslave][INFO] 2017-10-13 16:36:14,487: _ready: http://wks-51-57:36088/
[xmlrpc][INFO] 2017-10-13 16:36:14,487: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-13 16:36:14,488: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-10-13 16:36:14,587: registered with master
[rospy.rosout][INFO] 2017-10-13 16:36:14,587: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-13 16:36:14,610: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-13 16:36:14,615: initializing /clock core topic
[rospy.simtime][INFO] 2017-10-13 16:36:14,619: connected to core topic /clock
[rospy.internal][INFO] 2017-10-13 16:36:14,718: topic[/all_distances] adding connection to [http://wks-51-57:36876/], count 0
[rospy.internal][INFO] 2017-10-13 16:36:14,800: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-13 16:36:14,832: topic[/clock] adding connection to [http://wks-51-57:36634/], count 0
[rospy.internal][INFO] 2017-10-13 16:36:14,833: topic[/all_distances] adding connection to [http://wks-51-57:42313/], count 1
[rospy.internal][ERROR] 2017-10-13 16:40:45,295: Unable to initiate TCP/IP socket to wks-51-57:40216 (http://wks-51-57:42313/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2017-10-13 16:40:45,299: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-10-13 16:40:45,308: Unable to initiate TCP/IP socket to wks-51-57:38628 (http://wks-51-57:36876/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-13 16:40:45,313: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-13 16:40:45,314: topic[/clock] removing connection to http://wks-51-57:36634/
[rospy.internal][INFO] 2017-10-13 16:40:45,315: topic[/all_distances] removing connection to http://wks-51-57:36876/
[rospy.internal][INFO] 2017-10-13 16:40:45,315: topic[/all_distances] removing connection to http://wks-51-57:42313/
[rospy.impl.masterslave][INFO] 2017-10-13 16:40:45,315: signal-2
[rospy.core][INFO] 2017-10-13 16:40:45,479: signal_shutdown [atexit]
